# Generated by Django 2.2.4 on 2020-04-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handy_helper_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
