# Generated by Django 2.2.4 on 2020-04-24 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy_helper_app', '0003_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='users',
        ),
        migrations.AddField(
            model_name='job',
            name='uploaded_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='job_uploaded_by', to='handy_helper_app.User'),
            preserve_default=False,
        ),
    ]
