# Generated by Django 2.2.4 on 2020-04-24 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy_helper_app', '0004_auto_20200424_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_job', to='handy_helper_app.User'),
        ),
    ]
