# Generated by Django 2.2.4 on 2020-04-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handy_helper_app', '0007_auto_20200425_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='users',
        ),
    ]
